-- SignalCore Sales OS V1
-- Public lead discovery, deterministic qualification and CRM pipeline.

create table if not exists public.sales_campaigns (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  status text not null default 'draft'
    check (status in ('draft','active','paused','completed','archived')),
  country text,
  industry text,
  location_code integer not null default 2840,
  language_code text not null default 'en',
  queries jsonb not null default '[]'::jsonb,
  exclusions jsonb not null default '[]'::jsonb,
  depth integer not null default 20 check (depth between 10 and 100),
  min_score integer not null default 65 check (min_score between 0 and 100),
  max_candidates integer not null default 100 check (max_candidates between 1 and 1000),
  max_run_cost_usd numeric(10,4) not null default 0.25 check (max_run_cost_usd >= 0),
  last_run_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_leads (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  domain text not null,
  company_name text,
  country text,
  industry text,
  stage text not null default 'discovered'
    check (stage in ('discovered','qualified','audited','contact_found','outreach_ready','contacted','replied','meeting','proposal','won','lost','rejected')),
  qualification_status text not null default 'pending'
    check (qualification_status in ('pending','qualified','rejected','needs_review')),
  score integer not null default 0 check (score between 0 and 100),
  score_breakdown jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  notes text,
  converted_project_id uuid,
  last_qualified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id,domain),
  foreign key(converted_project_id,owner_id)
    references public.projects(id,owner_id) on delete set null
);

create table if not exists public.sales_campaign_leads (
  campaign_id uuid not null references public.sales_campaigns(id) on delete cascade,
  lead_id uuid not null references public.sales_leads(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  source_query text,
  source_rank integer,
  source_url text,
  discovered_at timestamptz not null default now(),
  primary key(campaign_id,lead_id)
);

create table if not exists public.sales_contacts (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.sales_leads(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text,
  role text,
  email text,
  phone text,
  source text,
  verification_status text not null default 'unverified',
  is_primary boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.sales_leads(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_discovery_runs (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.sales_campaigns(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'running',
  queries_requested integer not null default 0,
  queries_completed integer not null default 0,
  candidates_seen integer not null default 0,
  leads_created integer not null default 0,
  leads_linked integer not null default 0,
  actual_cost numeric(10,4) not null default 0,
  result jsonb not null default '{}'::jsonb,
  error text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

-- Production rollout enables owner-scoped RLS, grants and covering indexes.
